In [2]:
from numpy    import *
from spectrum import *

# Using Spectrum class

In [3]:
eng1 = logspace(0.,3.,num = 500)
dNdE1 = logspace(0.,5.,num = 500)

eng2   = logspace(0.,3.,num=2)
dNdE2 = logspace(0.,5.,num=2)

testMat = array([[1,2],[2,1]])

rs = 2000.

specObj1 = Spectrum(eng1,dNdE1,rs)
specObj2 = Spectrum(eng2,dNdE2,rs)

print('*** Testing addition and scalar multiplication of Spectrum ***')
print('specObj2 spectrum: ')
print(specObj2.dNdE)


print('Contract specObj2 with [[1,2],[2,1]] row-wise:')
print(specObj2.contract(testMat))
specObj3 = 5*specObj2
specObj4 = -specObj2*5
print('Multiply specObj2 by 5 (5* and - *5): ')
print(specObj3.dNdE)
print(specObj4.dNdE)
print('Add [10,10] to specObj3 (on both sides): ')
specObj5 = specObj3 + array([10,10])
print(specObj5.dNdE)
specObj6 = array([1,10]) + specObj3
print(specObj6.dNdE)
print('Check abscissa unaffected: ')
print(specObj2.eng)
print(specObj3.eng)

print('*** Test totN and toteng ***')

print('Compare direct computation of sum with totN(): ')
print(sum(specObj1.dNdE*specObj1.eng*specObj1.binWidth))
print(specObj1.totN())
print('Compare direct computation of energy with toteng(): ')
print(sum(specObj1.dNdE*specObj1.eng**2*specObj1.binWidth))
print(specObj1.toteng())

print('*** Test redshifting ***')

initTotN   = specObj1.totN()
initTotEng = specObj1.toteng()


print('Initial N: '+str(initTotN))
print('Initial Energy: '+str(initTotEng))

finRedshift = 1310
specObj1.redshift(finRedshift)


print('** Redshift from '+str(rs)+' to '+str(finRedshift)+'**')

finTotN   = specObj1.totN()
finTotEng = specObj1.toteng()

print('Final N: '+str(finTotN))
print('Final Energy: '+str(finTotEng))

print('Redshifting ratio: '+str(2000/finRedshift))
print('Energy ratio: '+str(initTotEng/finTotEng))

rs = finRedshift
finRedshift = 6
specObj1.redshift(finRedshift)


print('** Redshift from '+str(rs)+' to '+str(finRedshift)+'**')

initTotN = finTotN
initTotEng = finTotEng

finTotN   = specObj1.totN()
finTotEng = specObj1.toteng()

print('Final N: '+str(finTotN))
print('Final Energy: '+str(finTotEng))

print('Redshifting ratio: '+str(rs/finRedshift))
print('Energy ratio: '+str(initTotEng/finTotEng))

print('Check division by 5 on underflow bins (implemented as multiplication on the right by 1/5): ')
specObj1 = specObj1/5
finTotN2   = specObj1.totN()
finTotEng2 = specObj1.toteng()

print('Final N/Previous N: '+str(finTotN2/finTotN))
print('Final Energy/Previous Energy: '+str(finTotEng2/finTotEng))
# print('*******************')


*** Testing addition and scalar multiplication of Spectrum ***
specObj2 spectrum: 
[  1.00000000e+00   1.00000000e+05]
Contract specObj2 with [[1,2],[2,1]] row-wise:
[ 200001.  100002.]
Multiply specObj2 by 5 (5* and - *5): 
[  5.00000000e+00   5.00000000e+05]
[ -5.00000000e+00  -5.00000000e+05]
Add [10,10] to specObj3 (on both sides): 
[  1.50000000e+01   5.00010000e+05]
[  6.00000000e+00   5.00010000e+05]
Check abscissa unaffected: 
[    1.  1000.]
[    1.  1000.]
*** Test totN and toteng ***
Compare direct computation of sum with totN(): 
38196417.9184
38196417.9184
Compare direct computation of energy with toteng(): 
27970742355.1
27970742355.1
*** Test redshifting ***
Initial N: 38196417.9184
Initial Energy: 27970742355.1
** Redshift from 2000.0 to 1310**
Final N: 38196417.9184
Final Energy: 18321267904.3
Redshifting ratio: 1.5267175572519085
Energy ratio: 1.52668158673
** Redshift from 1310 to 6**
Final N: 38196417.9184
Final Energy: 83914810.3641
Redshifting ratio: 218.333333333

# Using Spectra class

In [4]:
eng   = logspace(0.,3.,num=4)
rs    = flipud(logspace(1.,3.,num=3))

specList = ([Spectrum(eng,logspace(0.,3.,num=4),rs[0]), 
             Spectrum(eng,logspace(0.,6.,num=4),rs[1]), 
             Spectrum(eng,logspace(0.,9.,num=4),rs[2])
             ])

testArr1 = [[10,0,0,0],[0,10,0,0],[0,0,10,0]]

testArr = ([Spectrum(eng,array([10,0,0,0]),rs[0]),
                Spectrum(eng,array([0,10,0,0]),rs[1]),
                Spectrum(eng,array([0,0,10,0]),rs[2])]
           )
testArr2 = array([4, 3, 7, 1])
testArr3 = array([3, 5, 6])

spectra = Spectra(rs,eng,specList)

print('*** Original Spectra ***')
print('Energy Abscissa: '+str(spectra.eng))
print('Redshift Abscissa: '+str(spectra.rs))
print(vstack([spec.dNdE for spec in spectra.spectrumList]))

print('*** Testing Sums ***')
print('Adding [[10,0,0,0],[0,10,0,0],[0,0,10,0]] to spectrum above:')
spectra2 = spectra + Spectra(rs,eng,testArr)
print(vstack([spec.dNdE for spec in spectra2.spectrumList]))
print('Adding [10,0,0,0] to each spectrum above:')
spectra3 = array([10,0,0,0]) + spectra
print(vstack([spec.dNdE for spec in spectra3.spectrumList]))

print('*** Testing Matrix Multiplications ***')
print('** Multiply spectrum by [4,3,7,1] **')
spectra4 = spectra*testArr2
print(vstack([spec.dNdE for spec in spectra4.spectrumList]))

print('*** Testing Re-Weighting Sum ***')
print('** Sum of spectra weighted by [3,5,6] **')
spectra5 = Spectra(rs,eng,specList)
spectrum5 = spectra5.sumbyrsweight(testArr3)
print(spectrum5.dNdE)
print(spectrum5.rs)

spectrum5.redshift(9)
print('*** Testing Appending Spectra above after redshifting to 1+z = 9 ***')
print('** Print the redshifted spectrum **')
print(spectrum5.dNdE)
print('** Print the appended spectrum **')
spectra5.append(spectrum5)
print(vstack([spec.dNdE for spec in spectra5.spectrumList]))
print(spectra5.rs)

*** Original Spectra ***
Energy Abscissa: [    1.    10.   100.  1000.]
Redshift Abscissa: [ 1000.   100.    10.]
[[  1.00000000e+00   1.00000000e+01   1.00000000e+02   1.00000000e+03]
 [  1.00000000e+00   1.00000000e+02   1.00000000e+04   1.00000000e+06]
 [  1.00000000e+00   1.00000000e+03   1.00000000e+06   1.00000000e+09]]
*** Testing Sums ***
Adding [[10,0,0,0],[0,10,0,0],[0,0,10,0]] to spectrum above:
[[  1.10000000e+01   1.00000000e+01   1.00000000e+02   1.00000000e+03]
 [  1.00000000e+00   1.10000000e+02   1.00000000e+04   1.00000000e+06]
 [  1.00000000e+00   1.00000000e+03   1.00001000e+06   1.00000000e+09]]
Adding [10,0,0,0] to each spectrum above:
[[  1.10000000e+01   1.00000000e+01   1.00000000e+02   1.00000000e+03]
 [  1.10000000e+01   1.00000000e+02   1.00000000e+04   1.00000000e+06]
 [  1.10000000e+01   1.00000000e+03   1.00000000e+06   1.00000000e+09]]
*** Testing Matrix Multiplications ***
** Multiply spectrum by [4,3,7,1] **
[[  4.00000000e+00   3.00000000e+01   7.0000